version: "3.8"

services:
  web:
    image: alecfut07/gamezone-web:latest
    container_name: web
    depends_on:
      - api
    env_file:
      - web.env
    ports:
      - "80:80"
    networks:
      - datazone-network

  api:
    image: alecfut07/gamezone-api:latest
    container_name: api
    depends_on:
      - db
      - redis
    env_file:
      - api.env
    ports:
      - 5248:5248
    networks:
      - datazone-network
      - data-network

  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: db
    restart: always
    env_file:
      - db.env
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - data-network
    volumes:
      - db-volume:/var/opt/mssql

  redis:
    image: redis:7.0.11
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - data-network
    volumes:
      - redis-volume:/data

networks:
  datazone-network:
    driver: bridge
  data-network:
    driver: bridge

volumes:
  db-volume:
    driver: local
  redis-volume:
    driver: local
